<a href="https://colab.research.google.com/github/Murari0323/numpy_tekworks/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print(2+2)

4


In [18]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)
arr_3d=np.array([[[6,7,8],[23,4,5]],[[22,45,6],[21,7,8]]])
print(arr_3d)
print(arr_3d.ndim)
print(arr_2d.ndim)
print(arr.ndim)
print(arr_2d.shape)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[[ 6  7  8]
  [23  4  5]]

 [[22 45  6]
  [21  7  8]]]
3
2
1
(2, 3)


In [17]:
import numpy as np
zeros=np.zeros((2,3))
print(zeros)
ones=np.ones((3,3))
print(ones)
random=np.random.random((2,2))
print(random)
eyes=np.eye((3))
print(eyes)
rangee=np.arange(1,10,3)
print(rangee)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.06137629 0.50301375]
 [0.00266941 0.94596504]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1 4 7]


In [21]:
import numpy as np

arr1=np.array([[4,6,7],[3,7,8]])
print(arr1.size)
print(arr1.dtype)
print(arr1.shape)
print(arr1.ndim)

6
int64
(2, 3)
2


In [27]:
import numpy as np
temp_data=np.array([[22,25,20],[24,26,23]])
print(temp_data.shape)
print(temp_data.size)
print(temp_data.ndim)
print(temp_data.dtype)
temp_data = np.append(temp_data, [[21, 23, 22]], axis=0)
updated_temp_data=temp_data
print(updated_temp_data)
sensor_error_flags=np.zeros((2,3))
greenhouse_identity=np.eye(3)
print(sensor_error_flags)
print(greenhouse_identity)

(2, 3)
6
2
int64
[[22 25 20]
 [24 26 23]
 [21 23 22]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [42]:
import numpy as np
shipments=np.array([[50,60,55,70,65,80,90],[40,45,50,60,55,70,75]])
print(shipments)
print(shipments[0,2])
print(shipments[1,6])
print(shipments[:,0:5])
print(shipments[:,5:])
print(shipments[0,2:6])
shipments[0,5]=100
print(shipments)

[[50 60 55 70 65 80 90]
 [40 45 50 60 55 70 75]]
55
75
[[50 60 55 70 65]
 [40 45 50 60 55]]
[[80 90]
 [70 75]]
[55 70 65 80]
[[ 50  60  55  70  65 100  90]
 [ 40  45  50  60  55  70  75]]


In [49]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
print(c)
print(a*b)
print(a*2)
print(np.dot(a,b))
d=np.array([[1,6,7],[4,9,8]])
e=np.array([[23,4,5],[6,80,4],[2,5,7]])
print(np.dot(d,e))

[5 7 9]
[ 4 10 18]
[2 4 6]
32
[[ 73 519  78]
 [162 776 112]]


In [51]:
a=np.array([1,2,3])
b=2
print(a+b)
print(np.exp(a))
print(np.sqrt(a))
print(np.log(a))

[3 4 5]
[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]


In [52]:
import numpy as np

# ---------------------------
# 1️⃣ Arithmetic ufuncs
# ---------------------------
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print("=== Arithmetic ufuncs ===")
print("Add:", np.add(x, y))
print("Subtract:", np.subtract(x, y))
print("Multiply:", np.multiply(x, y))
print("Divide:", np.divide(y, x))
print("Power:", np.power(x, 2))
print("Modulus:", np.mod(y, 4))
print()

# ---------------------------
# 2️⃣ Exponential & Logarithmic ufuncs
# ---------------------------
print("=== Exponential & Logarithmic ufuncs ===")
a = np.array([1, 2, 3])
print("exp:", np.exp(a))
print("log:", np.log(a))
print("log10:", np.log10(a))
print("log2:", np.log2(a))
print("expm1:", np.expm1(a))  # exp(x) - 1
print()

# ---------------------------
# 3️⃣ Trigonometric ufuncs
# ---------------------------
print("=== Trigonometric ufuncs ===")
angles = np.array([0, np.pi/4, np.pi/2])
print("sin:", np.sin(angles))
print("cos:", np.cos(angles))
print("tan:", np.tan(angles))
print("arcsin(1):", np.arcsin(1))
print("degrees(pi):", np.degrees(np.pi))
print("radians(180):", np.radians(180))
print()

# ---------------------------
# 4️⃣ Rounding ufuncs
# ---------------------------
print("=== Rounding ufuncs ===")
nums = np.array([1.2, 2.5, 3.7, -1.3])
print("Round:", np.round(nums))
print("Floor:", np.floor(nums))
print("Ceil:", np.ceil(nums))
print("Trunc:", np.trunc(nums))
print()

# ---------------------------
# 5️⃣ Statistical ufuncs
# ---------------------------
print("=== Statistical ufuncs ===")
data = np.array([2, 5, 7, 10])
print("Min:", np.min(data))
print("Max:", np.max(data))
print("Mean:", np.mean(data))
print("Std Dev:", np.std(data))
print("Variance:", np.var(data))
print("Sum:", np.sum(data))
print("Product:", np.prod(data))
print()

# ---------------------------
# 6️⃣ Logical ufuncs
# ---------------------------
print("=== Logical ufuncs ===")
p = np.array([True, False, True])
q = np.array([True, True, False])
print("Logical AND:", np.logical_and(p, q))
print("Logical OR:", np.logical_or(p, q))
print("Logical NOT (p):", np.logical_not(p))
print("Logical XOR:", np.logical_xor(p, q))
print()

# ---------------------------
# 7️⃣ Comparison ufuncs
# ---------------------------
print("=== Comparison ufuncs ===")
m = np.array([10, 20, 30])
n = np.array([15, 20, 25])
print("Greater:", np.greater(m, n))
print("Less:", np.less(m, n))
print("Equal:", np.equal(m, n))
print("Not Equal:", np.not_equal(m, n))
print("Greater Equal:", np.greater_equal(m, n))
print("Less Equal:", np.less_equal(m, n))
print()

# ---------------------------
# 8️⃣ Bitwise ufuncs
# ---------------------------
print("=== Bitwise ufuncs ===")
r = np.array([6], dtype=np.int32)  # binary: 110
s = np.array([3], dtype=np.int32)  # binary: 011
print("Bitwise AND:", np.bitwise_and(r, s))  # 110 & 011 = 010 (2)
print("Bitwise OR:", np.bitwise_or(r, s))    # 110 | 011 = 111 (7)
print("Bitwise XOR:", np.bitwise_xor(r, s))  # 110 ^ 011 = 101 (5)
print("Bitwise NOT (~6):", np.invert(r))     # ~6 = -7 (two's complement)


=== Arithmetic ufuncs ===
Add: [5 7 9]
Subtract: [-3 -3 -3]
Multiply: [ 4 10 18]
Divide: [4.  2.5 2. ]
Power: [1 4 9]
Modulus: [0 1 2]

=== Exponential & Logarithmic ufuncs ===
exp: [ 2.71828183  7.3890561  20.08553692]
log: [0.         0.69314718 1.09861229]
log10: [0.         0.30103    0.47712125]
log2: [0.        1.        1.5849625]
expm1: [ 1.71828183  6.3890561  19.08553692]

=== Trigonometric ufuncs ===
sin: [0.         0.70710678 1.        ]
cos: [1.00000000e+00 7.07106781e-01 6.12323400e-17]
tan: [0.00000000e+00 1.00000000e+00 1.63312394e+16]
arcsin(1): 1.5707963267948966
degrees(pi): 180.0
radians(180): 3.141592653589793

=== Rounding ufuncs ===
Round: [ 1.  2.  4. -1.]
Floor: [ 1.  2.  3. -2.]
Ceil: [ 2.  3.  4. -1.]
Trunc: [ 1.  2.  3. -1.]

=== Statistical ufuncs ===
Min: 2
Max: 10
Mean: 6.0
Std Dev: 2.9154759474226504
Variance: 8.5
Sum: 24
Product: 700

=== Logical ufuncs ===
Logical AND: [ True False False]
Logical OR: [ True  True  True]
Logical NOT (p): [False  True F

In [1]:
import numpy as np

# ---------------------------
# 1️⃣ Create 2D arrays for each farm (4 panels × 3 hours)
# ---------------------------
farmA = np.array([[10, 12, 11],
                  [9, 11, 10],
                  [12, 13, 14],
                  [8, 7, 9]])

farmB = np.array([[20, 19, 21],
                  [18, 20, 19],
                  [22, 23, 21],
                  [17, 18, 16]])

farmC = np.array([[15, 16, 14],
                  [14, 13, 15],
                  [16, 17, 18],
                  [12, 11, 13]])

# Stack into 3D array (3 farms × 4 panels × 3 hours) as float
production_all = np.stack([farmA, farmB, farmC], axis=0).astype(float)
print("production_all array:\n", production_all)
print("-"*30)

# ---------------------------
# 2️⃣ Array attributes
# ---------------------------
print("Array attributes:")
print("Shape:", production_all.shape)   # (3,4,3)
print("Size:", production_all.size)     # 36 elements
print("Dtype:", production_all.dtype)   # float64
print("Dimensions:", production_all.ndim)
print("-"*30)

# ---------------------------
# 3️⃣ Per-farm aggregation
# ---------------------------
total_per_farm = np.sum(production_all, axis=(1,2))
mean_per_farm  = np.mean(production_all, axis=(1,2))
std_per_farm   = np.std(production_all, axis=(1,2))
var_per_farm   = np.var(production_all, axis=(1,2))

print("Total per farm:", total_per_farm)
print("Mean per farm:", mean_per_farm)
print("Std per farm:", std_per_farm)
print("Variance per farm:", var_per_farm)
print("-"*30)

# ---------------------------
# 4️⃣ Per-hour weighted estimate (matrix multiplication)
# ---------------------------
hour_weights = np.array([0.5, 1.0, 0.75])
weighted_per_panel = np.dot(production_all, hour_weights)
print("Weighted per panel (per farm):\n", weighted_per_panel)
print("-"*30)

# ---------------------------
# 5️⃣ Broadcasting adjustments (offset +0.5 for Farm B)
# ---------------------------
production_all[1,:,:] += 0.5
print("production_all after Farm B offset:\n", production_all)
print("-"*30)

# ---------------------------
# 6️⃣ Z-score normalization per farm
# ---------------------------
normalized_data = (production_all - mean_per_farm[:, np.newaxis, np.newaxis]) / std_per_farm[:, np.newaxis, np.newaxis]
print("Z-score normalized data:\n", normalized_data)
print("-"*30)

# ---------------------------
# 7️⃣ Apply element-wise ufuncs
# ---------------------------
# Exponential family
exp_data = np.exp(normalized_data)
expm1_data = np.expm1(normalized_data)
log_data = np.log(production_all + 1)
log10_data = np.log10(production_all + 1)
log2_data = np.log2(production_all + 1)

# Trigonometric ufuncs
sin_data = np.sin(normalized_data)
cos_data = np.cos(normalized_data)
tan_data = np.tan(normalized_data)
arcsin_data = np.arcsin(np.clip(normalized_data/np.max(np.abs(normalized_data)), -1, 1))
arccos_data = np.arccos(np.clip(normalized_data/np.max(np.abs(normalized_data)), -1, 1))
arctan_data = np.arctan(normalized_data)
deg_data = np.degrees(normalized_data)
rad_data = np.radians(normalized_data)

# Rounding
round_data = np.round(normalized_data)
floor_data = np.floor(normalized_data)
ceil_data = np.ceil(normalized_data)
trunc_data = np.trunc(normalized_data)

# Comparison & logical ufuncs
high_output = production_all > 20
even_hours_mask = (np.arange(3) % 2 == 0)  # columns 0,2
even_hours_mask_broadcast = even_hours_mask[np.newaxis, np.newaxis, :]
combined_and = np.logical_and(high_output, even_hours_mask_broadcast)
combined_or  = np.logical_or(high_output, even_hours_mask_broadcast)
combined_not = np.logical_not(high_output)
combined_xor = np.logical_xor(high_output, even_hours_mask_broadcast)

greater_equal_mask = np.greater_equal(production_all, 15)
less_mask = np.less(production_all, 12)

# Bitwise ufuncs
alerts = np.array([[1,0,1],
                   [0,0,1],
                   [1,1,0],
                   [0,1,0]])
alerts_3d = np.stack([alerts]*3, axis=0)
bitwise_and = np.bitwise_and(alerts_3d, 1)
bitwise_or  = np.bitwise_or(alerts_3d, 0)
bitwise_invert = np.bitwise_invert(alerts_3d)

# Arithmetic ufuncs
add_data = np.add(normalized_data, 2)
sub_data = np.subtract(normalized_data, 1)
mul_data = np.multiply(normalized_data, 3)
div_data = np.divide(normalized_data, 2)
power_data = np.power(normalized_data, 2)
mod_data = np.mod(production_all, 5)

# Aggregations
sum_exp = np.sum(exp_data)
mean_sin = np.mean(sin_data)

print("Sum of exp(normalized_data):", sum_exp)
print("Mean of sin(normalized_data):", mean_sin)
print("-"*30)

# ---------------------------
# 8️⃣ Broadcast-based summary: per-panel totals & maintenance
# ---------------------------
panel_totals_per_farm = np.sum(production_all, axis=2)
needs_maintenance = np.any(panel_totals_per_farm < 40, axis=1)
print("Panel totals per farm:\n", panel_totals_per_farm)
print("Needs maintenance per farm:", needs_maintenance)
print("-"*30)

# ---------------------------
# 9️⃣ Final KPIs
# ---------------------------
overall_total = np.sum(production_all)
peak_hour_value = np.max(production_all)
peak_idx_flat = np.argmax(production_all)
peak_farm, peak_panel, peak_hour = np.unravel_index(peak_idx_flat, production_all.shape)
average_per_panel = np.mean(production_all, axis=2)

print("Overall total energy:", overall_total)
print(f"Peak hour value: {peak_hour_value} produced by Farm {peak_farm}, Panel {peak_panel}, Hour {peak_hour}")
print("Average per panel across hours:\n", average_per_panel)


production_all array:
 [[[10. 12. 11.]
  [ 9. 11. 10.]
  [12. 13. 14.]
  [ 8.  7.  9.]]

 [[20. 19. 21.]
  [18. 20. 19.]
  [22. 23. 21.]
  [17. 18. 16.]]

 [[15. 16. 14.]
  [14. 13. 15.]
  [16. 17. 18.]
  [12. 11. 13.]]]
------------------------------
Array attributes:
Shape: (3, 4, 3)
Size: 36
Dtype: float64
Dimensions: 3
------------------------------
Total per farm: [126. 234. 174.]
Mean per farm: [10.5 19.5 14.5]
Std per farm: [1.97905701 1.97905701 1.97905701]
Variance per farm: [3.91666667 3.91666667 3.91666667]
------------------------------
Weighted per panel (per farm):
 [[25.25 23.   29.5  17.75]
 [44.75 43.25 49.75 38.5 ]
 [34.   31.25 38.5  26.75]]
------------------------------
production_all after Farm B offset:
 [[[10.  12.  11. ]
  [ 9.  11.  10. ]
  [12.  13.  14. ]
  [ 8.   7.   9. ]]

 [[20.5 19.5 21.5]
  [18.5 20.5 19.5]
  [22.5 23.5 21.5]
  [17.5 18.5 16.5]]

 [[15.  16.  14. ]
  [14.  13.  15. ]
  [16.  17.  18. ]
  [12.  11.  13. ]]]
-----------------------------

In [2]:
a=np.array([1,2,3,4,5,6])
reshape=a.reshape((2,3))
print(reshape)

[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

# Stack along a new axis (0 → row, 1 → column)
c0 = np.stack([a,b], axis=0)  # shape (2,3)
c1 = np.stack([a,b], axis=1)  # shape (3,2)

print("axis=0:\n", c0)
print("axis=1:\n", c1)


axis=0:
 [[1 2 3]
 [4 5 6]]
axis=1:
 [[1 4]
 [2 5]
 [3 6]]


In [5]:
a = np.array([[1],[2]])
b = np.array([[3],[4]])
h = np.hstack([a,b])
print(h)
v = np.vstack([a,b])
print(v)
d = np.dstack([a,b])
print(d)


[[1 3]
 [2 4]]
[[1]
 [2]
 [3]
 [4]]
[[[1 3]]

 [[2 4]]]


In [6]:
arr = np.array([[1,2,3,4],
                [5,6,7,8]])

# Split into 2 arrays along columns (axis=1)
parts = np.split(arr, 2, axis=1)
print(parts[0])
print(parts[1])


[[1 2]
 [5 6]]
[[3 4]
 [7 8]]


In [10]:
arr = np.array([1,2,3,4,5])
parts = np.array_split(arr, 3)
print(parts)  # [array([1,2]), array([3,4]), array([5])]


[array([1, 2]), array([3, 4]), array([5])]


In [9]:
a=np.array([1,2,3,4,5])
print(arr[arr>2])
indices=[1,3]
print(arr[indices])

[3 4 5]
[2 4]


In [12]:
a=np.array([10,20,30])
print(a)
view=a.view()
view[0]=40
print(a)


[10 20 30]
[40 20 30]


In [13]:
a=np.array([10,20,30])
print(a)
copy=a.copy()
copy[0]=40
print(a)

[10 20 30]
[10 20 30]


In [14]:
a=np.array([1,2,3])
np.save('array.npy',a)
loaded_arr=np.load('array.npy')
print(loaded_arr)

[1 2 3]


TasksArray Creation
Create a 1D array of numbers from 10 to 50.
Create a 3x3 array of random numbers between 0 and 1.
Array Attributes
Find the shape, size, and data type of the array you created in the previous task.
Basic Operations
Add 5 to every element of a 1D array.
Multiply two 2D arrays element-wise.
Indexing and Slicing
Create a 5x5 array of integers from 1 to 25. Extract:
The first row.
The last column.
A subarray of the first three rows and first two columns.
Aggregation
Create a 10-element array of random integers between 10 and 100. Find:
The maximum value.
The minimum value.
The mean and standard deviation.
Reshaping
Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
Broadcasting
Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
Filtering
Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
Matrix Multiplication
Create two 2x2 matrices and perform matrix multiplication.
Advanced Indexing
Given a 4x4 array, use fancy indexing to extract the diagonal elements.

In [18]:
import numpy as np

# ---------------------------
# 1️⃣ Array Creation
# ---------------------------
# 1D array from 10 to 50
arr1d = np.arange(10, 51)
print("1D array:", arr1d)

# 3x3 array of random numbers between 0 and 1
arr3x3 = np.random.rand(3,3)
print("3x3 random array:\n", arr3x3)

# ---------------------------
# 2️⃣ Array Attributes
# ---------------------------
print("Shape:", arr3x3.shape)
print("Size:", arr3x3.size)
print("Data type:", arr3x3.dtype)

# ---------------------------
# 3️⃣ Basic Operations
# ---------------------------
# Add 5 to every element of 1D array
arr1d_plus5 = arr1d + 5
print("1D array +5:", arr1d_plus5)

# Multiply two 2D arrays element-wise
arrA = np.array([[1,2],[3,4]])
arrB = np.array([[5,6],[7,8]])
arr_mult = arrA * arrB
print("Element-wise multiplication:\n", arr_mult)

# ---------------------------
# 4️⃣ Indexing and Slicing
# ---------------------------
arr5x5 = np.arange(1,26).reshape(5,5)
print("5x5 array:\n", arr5x5)

first_row = arr5x5[0,:]
print("First row:", first_row)

last_col = arr5x5[:, -1]
print("Last column:", last_col)

subarray = arr5x5[:3, :2]
print("Subarray (first 3 rows, first 2 cols):\n", subarray)

# ---------------------------
# 5️⃣ Aggregation
# ---------------------------
rand10 = np.random.randint(10,101, size=10)
print("Random array:", rand10)

max_val = np.max(rand10)
min_val = np.min(rand10)
mean_val = np.mean(rand10)
std_val = np.std(rand10)

print("Max:", max_val, "Min:", min_val, "Mean:", mean_val, "Std:", std_val)

# ---------------------------
# 6️⃣ Reshaping
# ---------------------------
arr1d_12 = np.arange(1,13)
matrix3x4 = arr1d_12.reshape(3,4)
print("3x4 matrix:\n", matrix3x4)

# ---------------------------
# 7️⃣ Broadcasting
# ---------------------------
mat3x3 = np.ones((3,3))
row_vec = np.array([1,2,3])
broadcast_sum = mat3x3 + row_vec
print("Broadcasted sum:\n", broadcast_sum)

# ---------------------------
# 8️⃣ Filtering
# ---------------------------
rand_array = np.random.randint(1,51, size=10)
div5_elements = rand_array[rand_array % 5 == 0]
print("Random array:", rand_array)
print("Divisible by 5:", div5_elements)

# ---------------------------
# 9️⃣ Matrix Multiplication
# ---------------------------
matX = np.array([[1,2],[3,4]])
matY = np.array([[5,6],[7,8]])
mat_dot = np.dot(matX, matY)
print("Matrix multiplication:\n", mat_dot)

# ---------------------------
# 🔟 Advanced Indexing (fancy indexing)
# ---------------------------
arr4x4 = np.arange(1,17).reshape(4,4)
diagonal_elements = arr4x4[np.arange(4), np.arange(4)]
print("4x4 array:\n", arr4x4)
print("Diagonal elements:", diagonal_elements)


1D array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
3x3 random array:
 [[0.19292454 0.4604947  0.00339445]
 [0.99922424 0.81734262 0.46794848]
 [0.96964833 0.57606037 0.93225328]]
Shape: (3, 3)
Size: 9
Data type: float64
1D array +5: [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
Element-wise multiplication:
 [[ 5 12]
 [21 32]]
5x5 array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
First row: [1 2 3 4 5]
Last column: [ 5 10 15 20 25]
Subarray (first 3 rows, first 2 cols):
 [[ 1  2]
 [ 6  7]
 [11 12]]
Random array: [27 85 88 12 56 48 76 43 83 83]
Max: 88 Min: 12 Mean: 60.1 Std: 25.62206080704673
3x4 matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Broadcasted sum:
 [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
Random array: [44 39 19 11 17 36 48  2 23 23]
Divisible by 5: []
Matrix m